title: OSIUM (Open Science Initiative University Marburg) - DEV
description: Researchers from all career stages and disciplines, dedicated to promoting open science practices. 
show_downloads: true
theme: jekyll-theme-cayman
